### ISSUE TITLE
Add buy level is not possible anymore

### ISSUE THREAD

**Issue by offtopic** [MarcelBeining/EazeBot#11]
**Describe the bug**
After updating to v2.4.3 i can't add new buy levels

![image](https://user-images.githubusercontent.com/3337241/88703888-9c94d100-d10d-11ea-9411-029a2ef1ac25.png)
After clicking "no" -> nothing happens

An inactive trade set without any buy level

log file:

`2020-07-28 20:04:45,083 [Bot:73674776] [INFO ]  Finished updating trade sets...
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 816, in timing_callback
    return context.user_data['lastFct'].pop()(None)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 615, in <lambda>
    lambda res: self.ask_pos(bot, user_data, exch, uid_ts, direction, apply_fct, 'candleAbove', res))
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 642, in ask_pos
    return apply_fct()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 1103, in <lambda>
    'continue'))
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 1105, in inline_button_callback
    ct.add_buy_level(uid_ts, context.user_data['tempTradeSet'][0],
AttributeError: 'tradeHandler' object has no attribute 'add_buy_level'`

**System (please complete the following information):**
 - OS: Windows 10 64 bit
 - Version v2.4.3
 - Version of ccxt: 1.32.12

thx in advance, your bot is really great!

**Comment by offtopic** [comment]
I will switch to the docker version and come back to you

**Comment by offtopic** [comment]
Unfortunately same error

And one sidenote for installation: it was required to use elevated rights to start the docker file, is this indentionally?

`D:\apps\EazeBot\docker>docker-compose run --rm eazebot --init
ERROR: Cannot create container for service eazebot: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"   bei Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:Zeile 0.\r\n--- Ende der StapelĂĽberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelĂ¶st wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:Zeile 47.\r\n--- Ende der StapelĂĽberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelĂ¶st wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\FilesharingController.cs:Zeile 21.\r\n--- Ende der StapelĂĽberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelĂ¶st wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- Ende der StapelĂĽberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelĂ¶st wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- Ende der StapelĂĽberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelĂ¶st wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- Ende der StapelĂĽberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelĂ¶st wurde ---\r\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}
PS D:\apps\EazeBot\docker>`

**Comment by MarcelBeining** [comment]
Hi @offtopic ,
Thanks for reporting, I encountered the problem myself and are about to fix it tomorrow. Meanwhile you can switch back to version an older version. I apologize for the inconveniences.

**Comment by offtopic** [comment]
Wow, you are really fast with your feedback, thx in advance!

**Comment by MarcelBeining** [comment]
Fixed in [v.2.5.0](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.5.0)

**Comment by offtopic** [comment]
@MarcelBeining update to 2.5.0 -> with and withoud docker same error:

`Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\__main__.py", line 12, in <module>
    main.main()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\main.py", line 62, in main
    from eazebot.bot import EazeBot
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 41, in <module>
    from eazebot.tradeHandler import tradeHandler
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\tradeHandler.py", line 34, in <module>
    from eazebot.handling import ValueType, Price, BaseSL, DailyCloseSL, WeeklyCloseSL, TrailingSL, BaseTradeSet, \
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\handling.py", line 5, in <module>
    from dateparser import parse as dateparse
ModuleNotFoundError: No module named 'dateparser'`

**Comment by MarcelBeining** [comment]
Sorry, I should really start to use virtual environments for module requirement checks :-)
Fixed in [v.2.5.1](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.5.1)

**Comment by offtopic** [comment]
thx @MarcelBeining! it works now again - i know the problem -> "it works on my machine" -> i'm also a developer ;)

**Comment by offtopic** [comment]
@MarcelBeining unfortunately i found another issue on deleting trade set (the trade set is inactive, was never active)

`2020-07-30 16:58:55,971 [Bot:73674776] [INFO ]  Finished updating trade sets...
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "/eazebot_docker/eazebot/bot.py", line 1290, in inline_button_callback
    ts.delete_trade_set(sell_all='yes' in args)
AttributeError: 'BaseTradeSet' object has no attribute 'delete_trade_set'`

**Comment by MarcelBeining** [comment]
Please, in the future, open a new issue for new bugs!
Fixed in [v2.5.2](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.5.2)

**Comment by offtopic** [comment]
@MarcelBeining sorry, for sure, thx again
