### ISSUE TITLE
Error on deleting inactive trade set

### ISSUE THREAD

**Issue by offtopic** [MarcelBeining/EazeBot#13]
I get still an error on deleting an existing trade set, but a different error:

v2.5.2 (docker and standard version)

`No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eazebot\bot.py", line 1290, in inline_button_callback
    ct.delete_trade_set(sell_all='yes' in args)
TypeError: delete_trade_set() missing 1 required positional argument: 'i_ts'`

I have the greatest respect for your work, and I am very grateful for this wonderful bot!

**Comment by MarcelBeining** [comment]
Sorry, had no time to test the fix this morning as I had to leave for vacation. Cannot fix it until Tuesday :-/

**Comment by MarcelBeining** [comment]
Fixed in [v.2.5.3](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.5.3)

**Comment by offtopic** [comment]
Thank you very much, it works now!
Unfortunately i found a new error (but is minor) - will create a new issue
