### ISSUE TITLE
Issue with Deleting a Trade Set

### ISSUE THREAD

**Issue by sHaDoW8185** [MarcelBeining/EazeBot#2]
Hi again,

I came back from leaving the bot on overnight.  I received a few errors after trying to delete a tradeset that never executed since the price target was never reached.  Here is what I have:

2018-06-30 19:06:51,892 [job_queue   ] [INFO ]  Updating trade sets...
2018-06-30 19:06:51,892 [job_queue   ] [INFO ]  Finished updating trade sets...
2018-06-30 19:07:03,664 [dispatcher  ] [ERROR]  An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\ccxt\base\exchange.py", line 366, in fetch
    response.raise_for_status()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1530410823760&recvWindow=5000&symbol=ELFBTC&orderId=27401281&signature=b6e7aefe1b6e15c12fbe337d230b2e777248de662e4d599984632ea20f086527

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\telegram\ext\conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\telegram\ext\callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "c:\Run\EazeBot 1.2.15\eazebot\EazeBot.py", line 690, in InlineButtonCallback
    ct.deleteTradeSet(uidTS,sellAll='yes' in args)
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 367, in deleteTradeSet
    self.deactivateTradeSet(iTs,1)
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 237, in deactivateTradeSet
    self.cancelBuyOrders(iTs)
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 592, in cancelBuyOrders
    orderInfo = self.fetchOrder(trade['oid'],self.tradeSets[iTs]['symbol'],'BUY')
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 617, in fetchOrder
    return self.safeRun(lambda: self.exchange.fetchOrder (oid,symbol),0)
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 120, in safeRun
    raise(e)
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 114, in safeRun
    return func()
  File "c:\Run\EazeBot 1.2.15\eazebot\tradeHandler.py", line 617, in <lambda>
    return self.safeRun(lambda: self.exchange.fetchOrder (oid,symbol),0)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\ccxt\binance.py", line 697, in fetch_order
    response = self.privateGetOrder(self.extend(request, params))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\ccxt\binance.py", line 897, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\ccxt\base\exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\ccxt\base\exchange.py", line 378, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\ccxt\binance.py", line 890, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
2018-06-30 19:07:14,355 [MainThread  ] [INFO ]  Received signal 2 (SIGINT), stopping...
2018-06-30 19:07:17,432 [MainThread  ] [INFO ]  Created user data autosave backup
2018-06-30 19:07:17,450 [MainThread  ] [INFO ]  User data autosaved
2018-06-30 19:07:24,257 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-30 19:07:24,257 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-30 19:07:24,258 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-30 19:07:24,258 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-30 19:07:24,258 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-30 19:07:24,259 [MainThread  ] [INFO ]  Loading user data
2018-06-30 19:07:31,064 [dispatcher  ] [INFO ]  User Jacob Burbank-Goldrich (username: jbgoldrich, id: 999999999) (re)started the bot
2018-06-30 19:08:02,269 [dispatcher  ] [ERROR]  User 530658067: <class 'ccxt.base.errors.ExchangeError'> in tradeHandler.py at line 114: binance: unknown error code: {"code":-1104,"msg":"Not all sent parameters were read; read '5' parameter(s) but was sent '6'."} -1104

Trying to delete the tradeset consistently results in this error or other Timestamp errors.

**Comment by MarcelBeining** [comment]
Hi. It looks like your system time is out of sync with binance, see
https://github.com/ccxt/ccxt/issues/850

As I have added the therementioned adjustForTimeDifference feature, this however should only be problematic if you are using the same API key for multiple applications (e.g. my bot and another). Do you?

Also, please always state what version of Eazebot you are using right now because I update up to multiple times per day.

**Comment by sHaDoW8185** [comment]
I see. I don't run any other bots. That key has been used for more than one
thing, yes. I believe I've got it used for the bot and for autoview. That
might be the problem. My apologies, the version was 1.2.15, as I'd just
upgraded per your instructions. I will go ahead and make a new key
specifically for the bot. Thanks!

By the way, if I cancelled the trades that were initiated by the bot in the
exchange, because this bot was returning errors, when I try to delete the
tradeset in the bot afterwards (once I assign a new API key) will this be
an issue? Thanks!

**Comment by MarcelBeining** [comment]
> By the way, if I cancelled the trades that were initiated by the bot in the
exchange, because this bot was returning errors, when I try to delete the
tradeset in the bot afterwards (once I assign a new API key) will this be
an issue? Thanks!

Hm, it could be that the bot tries to reinitialize the orders. If you have not set important trade sets in your bot, yet, you can simply delete the files data.pickle and data.bkp. Then, the the bot forgot about all trade sets :-)

**Comment by MarcelBeining** [comment]
@sHaDoW8185 
I released a new version 1.3.0, which, upon other nice stuff, includes a fix compensating for system clocks which are regularly out of sync. This should fix your issue
