### ISSUE TITLE
sell error due to old version (v2.10)

### ISSUE THREAD

**Issue by offtopic** [MarcelBeining/EazeBot#45]
**Describe the bug**
Adding second sell order for binnace -> iota/btc fails on initializing sell order:

```
2021-04-17 11:25:00,714 [ThreadPoolEx] [ERROR]  Exchange Binance
<class 'ccxt.base.errors.InvalidOrder'> in                                     response = self.safe_run(lambda: self.exchange.createLimitSellOrder(ts.symbol,
 from tradeHandler.py at line 759: binance {"code":-1013,"msg":"Filter failure: PERCENT_PRICE"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 588, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/eazebot_docker/eazebot/bot.py", line 964, in update_trade_sets
    self.updater.dispatcher.user_data[user]['trade'][ex].update()
  File "/eazebot_docker/eazebot/tradeHandler.py", line 759, in update
    response = self.safe_run(lambda: self.exchange.createLimitSellOrder(ts.symbol,
  File "/eazebot_docker/eazebot/tradeHandler.py", line 224, in safe_run
    raise e
  File "/eazebot_docker/eazebot/tradeHandler.py", line 139, in safe_run
    return func()
  File "/eazebot_docker/eazebot/tradeHandler.py", line 759, in <lambda>
    response = self.safe_run(lambda: self.exchange.createLimitSellOrder(ts.symbol,
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1863, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/usr/local/lib/python3.8/site-packages/ccxt/binance.py", line 1667, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.8/site-packages/ccxt/binance.py", line 2475, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.8/site-packages/ccxt/binance.py", line 2469, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Filter failure: PERCENT_PRICE"}
2021-04-17 11:25:01,005 [ThreadPoolEx] [ERROR]  None
2021-04-17 11:25:01,637 [ThreadPoolEx] [INFO ]  Finished updating trade sets...


```

**System (please complete the following information):**
 - OS: Linux rasperry pi
 - Version eazebot: v2.10.1 (**i pulled the last changes but still on v2.10.1?**)
Bot info says: 
**There is a new version of EazeBot available on git/docker (v2.12.0) and PyPi with these changes:**

i think it's me, who made something wrong!

**Comment by MarcelBeining** [comment]
Hi @offtopic  and sorry for the late reply, I had issues with my Github 2FA authentication,
the PERCENT_PRICE error that binance responds to your order request means for the IOTA/BTC pair you entered a too high (or too low) sell price, e.g. more than 5 times higher than the current market price. Normally, EazeBot is checking all that restrictions when you add the sell order to a trading set, but it only occassionally reloads the restrictions from the exchanges. So it might have happened that Binance set new restrictions on the IOTA/BTC pair that EazeBot has not yet loaded from Binance.

Solutions:
- delete the sell order and add a not so high price for the sell
- before setting the new sell order hit the "Update exchanges" button in the EazeBot Telegram main menu, which will update all restrictions. Then EazeBot should tell you on order placement what is wrong with your order.
