### ISSUE TITLE
Error trying to get trade sets crex24

### ISSUE THREAD

**Issue by pavulon18** [MarcelBeining/EazeBot#9]
**Describe the bug**
A clear and concise description of what the bug is. Also copy and paste errors shown in Telegram, as well errors (from the time of the bug) shown in the telegramEazeBot.log file in your EazeBot folder.

This is the first time I have tried to run this bot.  I followed the install instructions as provided.  I started the bot, it seemed to start fine, with the exception of a couple of warnings.  These warnings have not been seen on subsequent bot starts.

I attempted to load all trading pairs from my exchange.  I then tried to assign a new trading pair.

The bot did not display my trading pairs as requested.  It also did not accept any trading pair entries that I manually entered.

Log file is shown at the end of this report.

Crex24 Exchange

**To Reproduce**
1. Start bot using this command:  sudo python3 startBotScript.py
2. Start the Telegram Bot
3. In Telegram, click "New Trade Set"
4. Click on "Crex24"

**Expected behavior**
I expected the bot to allow me to assign trade pairs.

**Screenshots**

**System (please complete the following information):**
 - OS: Raspbian Stretch on Raspberry Pi 3
 - Version eazebot: 1.9.10
 - Version of ccxt: 1.18.131
 - Exchange:  Crex24

**Additional context**

Error log from 
2019-02-26 14:56:33,182 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-26 14:56:33,184 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-26 14:56:33,236 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-26 14:56:33,237 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-26 14:56:33,239 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-26 14:56:33,243 [MainThread  ] [INFO ]  Loading user data
2019-02-26 14:56:35,282 [MainThread  ] [INFO ]  Found exchanges {'Crex24'} with keys ['Crex24'], secrets ['Crex24'], uids [], password []
2019-02-26 14:56:43,440 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-26 14:56:43,614 [job_queue   ] [ERROR]  local variable 'iTs' referenced before assignment
2019-02-26 14:56:43,615 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-26 14:56:47,903 [dispatcher  ] [INFO ]  User Jim Baize (username: None, id: 727599726) (re)started the bot
2019-02-26 14:57:08,887 [dispatcher  ] [WARNI]  A TelegramError was raised while processing the Update
2019-02-26 14:57:08,888 [dispatcher  ] [ERROR]  No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 157, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 655, in InlineButtonCallback
    query.edit_message_text('Choose a pair...',reply_markup=InlineKeyboardMarkup(buttons))
  File "/usr/local/lib/python3.5/dist-packages/telegram/callbackquery.py", line 141, in edit_message_text
    chat_id=self.message.chat_id, message_id=self.message.message_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 216, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 163, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response
2019-02-26 14:57:43,440 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-26 14:57:44,005 [job_queue   ] [ERROR]  local variable 'iTs' referenced before assignment
2019-02-26 14:57:44,006 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-26 14:58:43,440 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-26 14:58:43,966 [job_queue   ] [ERROR]  local variable 'iTs' referenced before assignment
2019-02-26 14:58:43,967 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-26 14:59:43,440 [job_queue   ] [INFO ]  Updating trade sets...

**Comment by MarcelBeining** [comment]
> I attempted to load all trading pairs from my exchange
What do you mean by that? Have you run EazeBot before on another system and want to transfer them to the raspberry? If yes did you copy the `data.pickle` ? If no, EazeBot is not able to take over orders that you set on the exchanges. You have to cancel them there and define them new in EazeBot.


> 2019-02-26 14:57:08,887 [dispatcher ] [WARNI] A TelegramError was raised while processing the Update
> 2019-02-26 14:57:08,888 [dispatcher ] [ERROR] No error handlers are registered, logging exception.
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 157, in _parse
> data = json.loads(decoded_s)
> File "/usr/lib/python3.5/json/**init**.py", line 319, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
> handler.handle_update(update, self)
> File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
> new_state = self.current_handler.handle_update(update, dispatcher)
> File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
> return self.callback(dispatcher.bot, update, **optional_args)
> File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 655, in InlineButtonCallback
> query.edit_message_text('Choose a pair...',reply_markup=InlineKeyboardMarkup(buttons))
> File "/usr/local/lib/python3.5/dist-packages/telegram/callbackquery.py", line 141, in edit_message_text
> chat_id=self.message.chat_id, message_id=self.message.message_id, *args, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 65, in decorator
> result = func(self, *args, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 90, in decorator
> result = self._request.post(url, data, timeout=kwargs.get('timeout'))
> File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 309, in post
> headers={'Content-Type': 'application/json'})
> File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 216, in _request_wrapper
> message = self._parse(resp.data)
> File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 163, in _parse
> raise TelegramError('Invalid server response')
> telegram.error.TelegramError: Invalid server response

That sounds to me like the telegram server did not respond correctly. This happens very rarely and has to do with Telegram. The solution is simply to retype your command or repress the desired button in telegram. However, be aware that due to lags or internet connection it can take up to 10 seconds until you get a response from EazeBot, so be patient with him and don't click wildly :-)

> 2019-02-26 14:58:43,966 [job_queue ] [ERROR] local variable 'iTs' referenced before assignment
Hm this part is something that should not happen. I'll check if I can reproduce this, however it would be helpful, if you answer the upper question and also tell me if my solution to the second part helps.

**Comment by MarcelBeining** [comment]
> 2019-02-26 14:58:43,966 [job_queue ] [ERROR] local variable 'iTs' referenced before assignment

I just committed a82ac59 and released [v1.9.11](https://github.com/MarcelBeining/EazeBot/releases/tag/EazeBot_1.9.11), which fixes the above bug. This bug actually masked the real error that seems to have occured in your case during updating the tradesets. If you install the update and restart the bot, we might see whats causing your problem in the error log.

**Comment by pavulon18** [comment]
I updated the bot.
when I pushed "Check Balance" I got this error message in Telegram:


    Error: Exchange CREX24
    <class 'ccxt.base.errors.BadRequest'> in             func = lambda sym: tickerssym if sym in tickers else ct.safeRun(lambda : ct.exchange.fetchTicker(sym))  # includes a hot fix for some ccxt problems
     from EazeBot.py at line 255: crex24 {"errorDescription":"Parameter 'instrument' contains invalid value."}


I then attempted to do a new Trade Set.  I clicked on "New Trade Set" then clicked on "List all pairs on Crex24".
I expected to see a list of the possible trading pairs, but maybe I misunderstood that command.

I was able to enter "ETH/BTC" and get an expected response.  This is something I was unable to get before.

I still got some error messages in my log file.

2019-02-27 07:43:35,200 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-27 07:43:35,239 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-27 07:43:35,240 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-27 07:43:35,242 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-27 07:43:35,243 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2019-02-27 07:43:35,248 [MainThread  ] [INFO ]  Loading user data
2019-02-27 07:43:37,350 [MainThread  ] [INFO ]  Found exchanges {'Crex24'} with keys ['Crex24'], secrets ['Crex24'], uids [], password []
2019-02-27 07:43:47,730 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-27 07:43:47,917 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-27 07:43:50,443 [dispatcher  ] [INFO ]  User Jim Baize (username: None, id: 727599726) (re)started the bot
2019-02-27 07:44:38,154 [dispatcher  ] [ERROR]  User 727599726: Exchange CREX24
<class 'ccxt.base.errors.BadRequest'> in             func = lambda sym: tickers[sym] if sym in tickers else ct.safeRun(lambda : ct.exchange.fetchTicker(sym))  # includ
es a hot fix for some ccxt problems
 from EazeBot.py at line 255: crex24 {"errorDescription":"Parameter 'instrument' contains invalid value."}
2019-02-27 07:44:38,840 [dispatcher  ] [ERROR]  An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 490, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.crex24.com/v2/public/tickers?instrument=CBTC-BTC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 709, in InlineButtonCallback
    return user_data['lastFct'].pop()(exch)
  File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 274, in <lambda>
    user_data['lastFct'].append(lambda res: checkBalance(bot,update,user_data,res))
  File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 268, in checkBalance
    elif BTCpair in ct.exchange.symbols and func(BTCpair)['last']*ct.balance['total'][c] > __config__['minBalanceInBTC']:
  File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 255, in <lambda>
    func = lambda sym: tickers[sym] if sym in tickers else ct.safeRun(lambda : ct.exchange.fetchTicker(sym))  # includes a hot fix for some ccxt problems
  File "/usr/local/lib/python3.5/dist-packages/eazebot/tradeHandler.py", line 215, in safeRun
    raise(e)
  File "/usr/local/lib/python3.5/dist-packages/eazebot/tradeHandler.py", line 140, in safeRun
    return func()
  File "/usr/local/lib/python3.5/dist-packages/eazebot/EazeBot.py", line 255, in <lambda>
    func = lambda sym: tickers[sym] if sym in tickers else ct.safeRun(lambda : ct.exchange.fetchTicker(sym))  # includes a hot fix for some ccxt problems
    File "/usr/local/lib/python3.5/dist-packages/ccxt/crex24.py", line 409, in fetch_ticker
    response = self.publicGetTickers(self.extend(request, params))
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 385, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 414, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 410, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 502, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/crex24.py", line 1136, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: crex24 {"errorDescription":"Parameter 'instrument' contains invalid value."}
2019-02-27 07:44:47,730 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-27 07:44:48,227 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-27 07:45:47,730 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-27 07:45:47,903 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-27 07:46:47,730 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-27 07:46:48,216 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-27 07:47:47,730 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-27 07:47:47,961 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-27 07:48:42,839 [job_queue   ] [INFO ]  Created user data autosave backup
2019-02-27 07:48:42,850 [job_queue   ] [INFO ]  User data autosaved
2019-02-27 07:48:47,730 [job_queue   ] [INFO ]  Updating trade sets...
2019-02-27 07:48:48,219 [job_queue   ] [INFO ]  Finished updating trade sets...
2019-02-27 07:49:16,439 [dispatcher  ] [WARNI]  A TelegramError was raised while processing the Update
2019-02-27 07:49:16,441 [dispatcher  ] [ERROR]  No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 157, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)

**Comment by MarcelBeining** [comment]
> when I pushed "Check Balance" I got this error message in Telegram:
> 
> ```
> Error: Exchange CREX24
> <class 'ccxt.base.errors.BadRequest'> in             func = lambda sym: tickerssym if sym in tickers else ct.safeRun(lambda : ct.exchange.fetchTicker(sym))  # includes a hot fix for some ccxt problems
>  from EazeBot.py at line 255: crex24 {"errorDescription":"Parameter 'instrument' contains invalid value."}
> ```

I reproduced the error with CREX24 and actually this is because your coin (CBTC according to the error log a few lines below) is currently or permanently deactivated for trading on CREX24. I made a new version which handles deactivated coins.

> I then attempted to do a new Trade Set. I clicked on "New Trade Set" then clicked on "List all pairs on Crex24".
> I expected to see a list of the possible trading pairs, but maybe I misunderstood that command.

Hm, in principle it should show you a message with as many buttons as there are trade pairs and then you can click on one of them. If the exchange has too many trading pairs the message gets too long and cannot be sent by Telegram. In that case only all symbols are shown as text and then you can type one of them as message, e.g. `ETH/BTC`. On some exchanges like binance, even only listing all trading pairs as text gets too long, so (in the new version) a message tells you about it. In this case, also type in your trading pair manually.

The remaining errors in your log should not appear anymore with the new release [1.9.14](https://github.com/MarcelBeining/EazeBot/releases/tag/EazeBot_1.9.14), except maybe that telegram error, which I talked about in the other post, but this is on the telegram server side.

Tell me if it is working now so I can close the issue =)
Feel free to open a new issue if other problems occur.

**Comment by pavulon18** [comment]
It appears that the original issue has been resolved.  Thank you for your quick and kind response.  I'm really hoping this bot fits the bill of what I need.

**Comment by MarcelBeining** [comment]
Great! Feel free to post issues and suggestions, star this project and spread the word :-)
